#!/usr/bin/env bash
# Display 1 - 100, Fizz for multiple of 3, Buzz for multiple of 5, and
#+ FizzBuzz for multiple of 3 and 5
for i in {1..100}
do
    if ((i%15 == 0))
    then
	echo "FizzBuzz"
    elif ((i%3 == 0))
    then
	echo "Fizz"
    elif ((i%5 == 0))
    then
	echo "Buzz"
    else
	echo $i
    fi
done
