#!/usr/bin/env bash
# First displays the hour and then minutes counting up to next hour
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -lt 60 ]
	do
		echo $minute
		((minute++))
	done
	((hour++))
done
